### ISSUE TITLE
ModuleNotFoundError: No module named 'neworder.domain'

### ISSUE THREAD

**Issue by platipodium** [virgesmith/neworder#63]
When running

`mpirun -np 4 python examples/n-body/model.py`

```
  File "/neworder/examples/n-body/n_body.py", line 5, in <module>
    from neworder.domain import Space
ModuleNotFoundError: No module named 'neworder.domain'
    from n_body import NBody
```

**Comment by platipodium** [comment]
@openjournals/joss-reviews#3351

**Comment by platipodium** [comment]
This is associated with [openjournals/joss-reviews#3351](https://github.com/openjournals/joss-reviews/issues/3351)

**Comment by virgesmith** [comment]
@platipodium can you confirm you're using it looks like you are using the latest *release* of the package with the bleeding edge version of the examples, which won't necessarily work (the domain stuff is a work-in-progress).

You have 2 options: use the released package with the versioned examples from the website (e.g. download link on https://neworder.readthedocs.io/en/stable/examples/n-body/), or build the latest version of the master branch in the repo - see  https://neworder.readthedocs.io/en/stable/developer/ and use the example code in the repo

**Comment by platipodium** [comment]
Well-spotted: using release package and bleeding edge examples...  I'll report back on this

**Comment by virgesmith** [comment]
@platipodium I'll close today this unless you respond otherwise

**Comment by platipodium** [comment]
Closing this
