### ISSUE TITLE
Add legal info for contributions

### ISSUE THREAD

**Issue by platipodium** [virgesmith/neworder#65]
There is no information how contributed code is handled.  Please clarify in your "Contributing" statement, how copyright is retained or transferred upon contributing to `neworder`

**Comment by platipodium** [comment]
@openjournals/joss-reviews#3351

**Comment by danielskatz** [comment]
ref: https://github.com/openjournals/joss-reviews/issues/3351  (this should work - it's a link, not a user...)

**Comment by virgesmith** [comment]
TBH I'm not sure what I need to add here, Do you know the legalese? along the lines of it's MIT and contributors retain copyright? or is that in itself enought?

**Comment by platipodium** [comment]
You need to make sure how to handle contributions to your software by people other than yourself.  E.g.  if I would contribute to `neworder` I would legally be an additional copyright holder to your software.  That in itself is (with MIT license and other FOSS) not a problem.

But it becomes a problem once you have contributions from several people (and therefore many copyright holders) and you would like to change the legal terms of your software, e.g., switching to Apache or GPL license or give some company an exclusive license under special terms.   To do this, you would require a unanimous consent by *all* copyright holders. 

To avoid this situation, it is customary to either transfer copyright (which many FOSS developers might dislike) or to retain copyright (which makes it difficult for the maintainer as stated above), or to seek a middle way that is, e.g., explained in detail on http://harmonyagreements.org/index.html

**Comment by virgesmith** [comment]
@platipodium pls confirm this resolves (or not) thanks

**Comment by virgesmith** [comment]
...now an extra "Legal" section here: https://neworder.readthedocs.io/en/latest/developer/

**Comment by platipodium** [comment]
Seems good to me
