### ISSUE TITLE
Refine `examples/requirements.txt`

### ISSUE THREAD

**Issue by tresoldi** [virgesmith/neworder#68]
Two suggestions. 

While it should be obvious to everybody in the target audience, it would be good to have a note in the installation instructions about how the examples need the libraries listed in `examples/requirements.txt`.

At the same time, it might be worth removing `mpi4py` from this `requirements.txt` file, as on platforms where it is not available `pip` will fail in the middle when invoked with a standard `pip -r examples/requirements.txt`. As there are only two examples using it (`parallel` and `options`) they could just fail requesting the installation of the library.

**Comment by virgesmith** [comment]
These are fair points. Most users should only need the requirements file if they are running the examples, and I shall make this clearer

**Comment by virgesmith** [comment]
I've chacked `mpi4py` and it's available for all the platforms that I state neworder is compatible with (linux, mac, win), so I don't think it needs special treatment.

**Comment by tresoldi** [comment]
Oh, fair point then. It did not work for me because I am in less favorable setting (Ubuntu Subsystem on an otherwise locked Windows, it might be possible to install `mpi` but did not work out-of-the-box), but it is an extreme case. I'm closing the issue.

**Comment by tresoldi** [comment]
Pinging JOSS https://github.com/openjournals/joss-reviews/issues/3351
