### ISSUE TITLE
How to learn neworder

### ISSUE THREAD

**Issue by zhangc927** [virgesmith/neworder#85]
Thank you for your excellent work. I am a PhD student majoring in economics, and I am interested in labor economics. I came across the microscopic simulation method and was very interested in it. Found your project on Github, but I have no basis in liam2, etc., just a bit familiar with economics and econometrics. I would like to ask about how to learn neworder comprehensively, because I have not found detailed documentation about neworder.

**Comment by virgesmith** [comment]
You'll find a link to the documentation at the end of the README
